version: "3.1"
# Este es un archivo de docker-compose.yml para configurar el uso de contenedores de software.

services:
  db:
    image: mysql
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: db_ecom_stock
      MYSQL_PASSWORD: 12345
    volumes:
      - .mysql_data:/var/lib/mysql:rw
    networks:
      - network1

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    ports:
      - 8080:80
    environment: 
      - PMA_ARBITRARY=1
    networks:
      - network1
    depends_on:
      - db
       
  prueba_django:
    # Imágen a utilizar:
    image: python:3.9.5
    # Nombre del container:
    container_name: prueba_djangoISDM
    # Comportamiento ante fallos y al iniciar el sistema:
    restart: always
    # Carpetas enlazadas:
    volumes:
      # Source code directory:
      - type: bind
        source: .
        target: /opt/back_end
    # Puertos enlazados:
    ports:
        - "8000:8000"
    # Control de consola:
    stdin_open: true
    tty: true
    networks:
      - network1

networks:
  network1:
    driver: bridge

volumes:
  mysql_data:  # Define el volumen para MySQL
