# Generated by Django 3.2.2 on 2024-08-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simpleweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo1', models.CharField(max_length=100)),
                ('campo2', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
